# Leaderboard
fragment leader on LeaderboardDTO {
  username
  avatar
  profitLoss
  rank
}

fragment leaderboardPDTO on LeaderboardPDTO {
  items {
    ...leader
  }
  hasMore
}

query Leaderboard($eLeaderboard: ELeaderboard!, $take: Int!, $skip: Int!, $seasonId: Int) {
  leaderboard(eLeaderboard: $eLeaderboard, take: $take, skip: $skip, seasonId: $seasonId) {
    ...leaderboardPDTO
  }
}

query MyLeaderboard($eLeaderboard: ELeaderboard!, $seasonId: Int) {
  myLeaderboard(eLeaderboard: $eLeaderboard, seasonId: $seasonId) {
    ...leader
  }
}
