# RedditMeme
fragment redditMeme on RedditMemeEntity {
  id
  title
  subreddit
  url
  redditId
  percentile
  redditBet {
    ...redditBet
  }
}

fragment paginatedRedditMemes on RedditMemePDTO {
  items {
    ...redditMeme
  }
  hasMore
}

query RedditMemeCount {
  redditMemeCount
}

query RandomRedditMemes($take: Int!, $skip: Int!) {
  randomRedditMemes(take: $take, skip: $skip) {
    ...redditMeme
  }
}
