# RedditMeme
fragment redditMeme on RedditMemeEntity {
  id
  title
  subreddit
  url
  redditId
  redditBet {
    ...redditBet
  }
}

fragment paginatedRedditMemes on RedditMemePDTO {
  items {
    ...redditMeme
  }
  hasMore
}

query RandomRedditMemes($take: Int!) {
  randomRedditMemes(take: $take) {
    ...redditMeme
  }
}
